<ul class="pagination">

    <li class="page-item">
        <a class="page-link" href="<?php echo $this->url(array("pagina" => $this->lastItemNumber)); ?>" aria-label="Previous">
            <span aria-hidden="true">«</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>
    <?php
    $i = 0;
    foreach ($this->pagesInRange as $page):
        $i++;
        if ($this->current == $page):
            ?>
            <li class="page-item active">
                <a class="page-link"><?php echo $page; ?></a>
            </li>
            <?php
        else:
            ?>
            <li class="page-item "><a class="page-link"
                                      href="<?php echo $this->url(array("pagina" => $page)); ?>"><?php echo $page; ?></a>
            </li>
            <?php
        endif;
    endforeach;
    ?>
    <li class="page-item">
        <a class="page-link" href="<?php echo $this->url(array("pagina" => $this->lastItemNumber)); ?>" aria-label="Next">
            <span aria-hidden="true">»</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
</ul>
