<div class="page-content aegis-page text-center">
    <div class="container-fluid">
        <div class="row">
            <?php foreach ($this->elencoUliveti as $uliveto): ?>
                <div
                    class="col-sm-6 col-md-12">
                    <section id="blockui-element-container-default" class="card">
                        <header class="card-header text-center">
                            <?php echo $uliveto['descrizione']; ?>
                        </header>
                        <div class="card-block display-table" style="max-height: 50px">
                            <div class="col-md-12">
                                <img src="<?php echo $this->baseUrl("public/adminBundle/img/olive.jpg"); ?>"
                                     width="100%" height="100%">
                            </div>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-warning"><?php echo $uliveto['descrizione']; ?></button>
                        </div>
                        <br>
                    </section>
                </div>
            <?php endforeach; ?>

        </div>
        <div class="text-center">
            <?php echo $this->paginationControl($this->elencoUliveti, 'Sliding', 'paginatore
            .phtml'); ?>
        </div>

    </div><!--.container-fluid-->

</div><!--.page-content-->
