<div class="page-content aegis-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12 dahsboard-column">
                <section class="card">
                    <header class="card-header text-center">
                        Aggiorna i parametri di sistema
                    </header>
                    <div class="card-block">
                        <?php echo $this->parametriForm; ?>
                    </div>
                </section>
            </div><!--.col-->
        </div>
    </div><!--.container-fluid-->
</div><!--.page-content-->
