<div class="page-content aegis-page">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xl-12">
				<div class="row">
					<div class="col-sm-4 col-md-4">
						<article class="statistic-box olive-oil">
							<div>
								<div class="number"><?php echo $this->temperaturaMedia;?></div>
								<div class="caption">
									<div>Temperatura Media</div>
								</div>
								<div class="percent">
									<div class="arrow up"></div>
									<p>15%</p>
								</div>
							</div>
						</article>
					</div><!--.col-->
					<div class="col-sm-4 col-md-4">
						<article class="statistic-box olive-oil">
							<div>
								<div class="number"><?php echo $this->umiditaMedia;?></div>
								<div class="caption">
									<div>Umidità media</div>
								</div>
								<div class="percent">
									<div class="arrow down"></div>
									<p>11%</p>
								</div>
							</div>
						</article>
					</div><!--.col-->
					<div class="col-sm-4 col-md-4">
						<article class="statistic-box olive-oil">
							<div>
								<div class="number"><?php echo $this->trappolaMedia;?></div>
								<div class="caption">
									<div>Conta delle mosche</div>
								</div>
								<div class="percent">
									<div class="arrow down"></div>
									<p>5%</p>
								</div>
							</div>
						</article>
					</div><!--.col-->
				</div><!--.row-->
			</div><!--.col-->
		</div><!--.row-->

		<div class="row">
			<div class="col-xl-12 dahsboard-column">
				<section class="card">
					<header class="card-header">
						Grafico dei sensori
					</header>
					<div class="card-block">
						<div id="area-chart"></div>
					</div>
				</section>
			</div><!--.col-->
			<div class="col-xl-12 dahsboard-column">
                <div class="col-lg-4">
                    <section class="card">
                        <header class="card-header">
                            Nodi malfunzionanti
                        </header>
                        <div class="card-block">
                            <div id="pie-chart"></div>
                        </div>
                    </section>
                </div>
                <div class="col-lg-4">
                    <section class="card">
                        <header class="card-header">
                            Stato dei nodi
                        </header>
                        <div class="card-block">
                            <div id="donut-chart"></div>
                        </div>
                    </section>
                </div>
                <div class="col-lg-4">
                    <section class="card">
                        <header class="card-header">
                            Nodi messi al sicuro
                        </header>
                        <div class="card-block">
                            <div id="gauge-chart"></div>
                        </div>
                    </section>
                </div>

			</div><!--.col-->
		</div>
	</div><!--.container-fluid-->
</div><!--.page-content-->

<script>
    var chart = c3.generate({
        "bindto": '#area-chart',
        data: {
            xs: {
                'umidita': 'date',
                'mosche': 'date'
            },
            colors: {
                umidita: '#c9b32c',
                mosche: '#46c35f'
            },
            types: {
                umidita: 'area-spline',
                mosche: 'area-spline'
            },
            columns: [
                <?php echo $this->dateUmidita; ?>
                <?php echo $this->valoriUmidita; ?>
                <?php echo $this->valoriMosche; ?>
            ]
        },
        axis: {
            x: {
                type: 'timeseries',
                tick: {
                    format: '%d-%m-%Y'
                }
            }
        }
    });
</script>
<script>var pieChart = c3.generate({
        bindto: '#pie-chart',
        data: {
            columns: [
                ['funzionanti', <?php echo ($this->percentualeSicuri + $this->percentualeAllertati + $this->percentualePericolosi) ; ?>],
                ['difettosi', <?php echo $this->percentualeMalfunzionanti; ?>]
            ],
            type: 'pie',
            colors: {
                funzionanti: '#2ecc71',
                difettosi: '#95a5a6'
            }
        }
    });
</script>
<script>
    var donutChart = c3.generate({
        bindto: '#donut-chart',
        data: {
            columns: [
                ['sicuri', <?php echo $this->percentualeSicuri; ?>],
                ['allertati', <?php echo $this->percentualeAllertati; ?>],
                ['insicuri', <?php echo $this->percentualePericolosi; ?>],
            ],
            type: 'donut',
            colors: {
                sicuri: '#2ecc71',
                allertati: '#e67e22',
                insicuri: '#e74c3c'
            }
        },
        donut: {
            title: "Stato dei nodi"
        },

    });
</script>
<script>
    var gaugeChart = c3.generate({
        bindto: '#gauge-chart',
        data: {
            columns: [
                ['data', <?php echo $this->percentualeSicuri; ?>]
            ],
            type: 'gauge',
        },
        gauge: {},
        color: {
            pattern: ['#FF0000', '#F97600', '#F6C600', '#60B044'], // the three color levels for the percentage values.
            threshold: {
                values: [30, 60, 90, 100]
            }
        },
        size: {
            height: 180
        }
    });
</script>
