<div class="page-content aegis-page text-center">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-12 text-center">
                <section id="blockui-element-container-default" class="card">
                    <header class="card-header text-center">
                        <?php echo $this->datiAppezzamento->nome; ?>
                    </header>
                    <br>
                    <br>
                    <br>
                    <div class="card-block display-table text-center" style="max-height: 50px">
                        <div class="col-md-12">
                            <img class="map" src="<?php echo $this->baseUrl("public/adminBundle/img/svg/background-olive.svg"); ?>" width="60%">
                            <br>
                            <br>
                            <img id="nodo1" class="tree" src="<?php echo $this->baseUrl("public/adminBundle/img/svg/tree-green.svg"); ?>">
                        </div>
                    </div>
                </section>
            </div>

        </div>

    </div><!--.container-fluid-->