<div class="page-content aegis-page text-center">
    <div class="container-fluid">
        <div class="row">
            <?php foreach ($this->elencoAppezzamenti as $appezzamento): ?>
                <div class="col-sm-6 col-md-6">
                    <section id="blockui-element-container-default" class="card">
                        <header class="card-header text-center">
                            <?php echo $appezzamento['nome']; ?>
                        </header>
                        <div class="card-block display-table" style="max-height: 50px">
                            <div class="col-md-12">
                                <img src="<?php echo $this->baseUrl("public/adminBundle/img/svg/background-olive.svg"); ?>"
                                     width="100%" height="100%">
                                <hr>
                                <?php echo $appezzamento['note']; ?>
                            </div>
                        </div>
                        <hr>
                        <div class="text-center">
                            <a href="<?php echo $this->url(array(
                                'controller' => 'user',
                                'action' => 'visualizza-nodi',
                                'appezzamento' => $appezzamento['idappezzamento']
                            )) ?>">
                                <button class="btn btn-warning"><?php echo $appezzamento['nome']; ?></button>
                            </a>
                        </div>
                        <br>
                    </section>
                </div>
            <?php endforeach; ?>

        </div>
        <div class="text-center">
            <?php echo $this->paginationControl($this->elencoAppezzamenti, 'Sliding', 'paginatore.phtml'); ?>
        </div>

    </div><!--.container-fluid-->

</div><!--.page-content-->
