<?php $uliveto = $this->uliveto; ?>
<div class="page-content aegis-page">
    <div class="container-fluid">

        <div class="col-xxl-12 col-lg-12 col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <section class="box-typical proj-page">
                <section class="proj-page-section proj-page-time-info">
                    <table id="datatable" class="table table-striped table-bordered " cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Appezzamento</th>
                            <th>Mappa</th>
                            <th>Note</th>
                            <th>Gestione Nodi</th>
                            <th>Modifica</th>
                            <th>Elimina</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Appezzamento</th>
                            <th>Mappa</th>
                            <th>Note</th>
                            <th>Gestione nodi</th>
                            <th>Modifica</th>
                            <th>Elimina</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        <?php
                        $i = 0;
                        foreach ($this->elencoAppezzamenti as $appezzamento):
                            $i++;
                            ?>
                            <tr>
                                <td><?php echo $i; ?></td>
                                <td style="text-transform: capitalize"><?php echo $appezzamento->nome; ?></td>
                                <td style="text-transform: capitalize"><?php echo $appezzamento->mappa; ?></td>
                                <td style="text-transform: capitalize"><?php echo $appezzamento->note; ?></td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(array(
                                        "controller" => "admin",
                                        "action" => "gestione-nodi",
                                        "uliveto" => $appezzamento->iduliveto,
                                        'appezzamento' => $appezzamento->idappezzamento),
                                        "default", true)
                                    ?>">
                                        <button type="button" class="btn btn-warning m-r-xs m-b-xs">Gestione Nodi
                                        </button>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(array(
                                        "controller" => "admin",
                                        "action" => "modifica-appezzamento",
                                        "uliveto" => $appezzamento->iduliveto,
                                        'appezzamento' => $appezzamento->idappezzamento),
                                        "default", true)
                                    ?>">
                                        <button type="button" class="btn btn-warning m-r-xs m-b-xs">Modifica Appezzamento
                                        </button>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em;">
                                    <a href="#">
                                        <button type="button" class="btn btn-danger m-r-xs m-b-xs elimina"
                                                id="<?php echo $appezzamento->idappezzamento; ?>">
                                            Elimina Appezzamento
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        $uliveto = $appezzamento->iduliveto;
                        endforeach;
                        ?>
                        </tbody>
                    </table>
                    <br>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <a href="<?php echo $this->url(array(
                                "controller" => "admin",
                                "action" => "inserisci-appezzamento",
                                "uliveto" => $uliveto),
                                "default", true)
                            ?>">
                                <button type="button" class="btn btn-uliveto m-r-xs m-b-xs">
                                    Inserisci un nuovo appezzamento
                                </button>
                            </a>
                        </div>
                    </div>
                </section><!--.proj-page-section-->
            </section><!--.proj-page-->
        </div>

    </div><!--.container-fluid-->
</div><!--.page-content-->

<script>
    $(document).ready(function () {
        $('#datatable').DataTable({
            "language": {
                "url": "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Italian.json"
            },
            "fnInitComplete": function (oSettings, json) {
                $("#datatable_filter").css("float", "right").css("width", "");
            }
        });

        $(".elimina").click(function (event) {
            event.preventDefault();
            var id = event.target.id;
            swal({
                    title: "Vuoi eliminare l'appezzamento?",
                    text: "Perderai tutti i nodi collegati!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Si, elimina!",
                    cancelButtonText: "No, annulla!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                function(isConfirm){
                    if (isConfirm) {
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array(
                                "controller" => "admin",
                                "action" => "elimina-appezzamento"),
                                "default", true);
                                ?>',
                            data:{appezzamento: id},
                            dataType: 'json',
                            success:function(){
                                swal("Eliminato!", "L'appezzamento è stato cancellato", "success");
                                setTimeout(window.location.replace("<?php echo $this->url(array(
                                        "controller" => "admin",
                                        "action" => "gestione-appezzamenti",
                                        "uliveto" => $this->uliveto),
                                        "default", true);
                                    ?>"),1000);
                            },
                            error: function (xhr) {
                                console.log("xhr",xhr.responseText);
                            }
                        })
                    } else {
                        swal("Annullato", "L'appezzamento non è stato cancellato", "error");
                    }
                });

        });

    });

</script>

