<div class="page-content aegis-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12 dahsboard-column">
                <section class="card">
                    <header class="card-header text-center">
                        Aggiorna i parametri di sistema
                    </header>
                    <div class="card-block">
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Categoria</th>
                                <th>Modifica</th>
                                <th>Elimina</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Categoria</th>
                                <th>Modifica</th>
                                <th>Elimina</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            $i=0;
                            foreach($this->categorie as $categoria):
                                $i++;
                                ?>
                                <tr>
                                    <td><?php echo $i;?></td>
                                    <td style="text-transform: capitalize"><?php echo $categoria->categoria;?></td>
                                    <td style="font-size: 1.2em;">
                                        <a href="<?php echo $this->url(array(
                                            "controller" => "admin",
                                            "action" => "modifica-categoria",
                                            "category"=> $categoria->idcategoria),
                                            "default",true)
                                        ?>"><button type="button" class="btn btn-primary m-r-xs m-b-xs">Modifica Categoria</button></a>
                                    </td>
                                    <td style="font-size: 1.2em;">
                                        <a href="<?php echo $this->url(array(
                                            "controller" => "admin",
                                            "action" => "elimina-categoria",
                                            "category"=> $categoria->idcategoria),
                                            "default",true)
                                        ?>"><button type="button" class="btn btn-danger m-r-xs m-b-xs">Elimina Categoria</button></a>
                                    </td>
                                </tr>
                                <?php
                            endforeach;
                            ?>
                            </tbody>
                        </table>
                    </div>
                </section>
            </div><!--.col-->
        </div>
    </div><!--.container-fluid-->
</div><!--.page-content-->