<div class="page-content aegis-page">
    <div class="container-fluid">

        <div class="col-xxl-12 col-lg-12 col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <section class="box-typical proj-page">
                <section class="proj-page-section proj-page-time-info">
                    <table id="datatable" class="table table-striped table-bordered " cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Uliveto</th>
                            <th>Modifica</th>
                            <th>Elimina</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Uliveto</th>
                            <th>Modifica</th>
                            <th>Elimina</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        <?php
                        $i = 0;
                        foreach ($this->elencoUliveti as $uliveto):
                            $i++;
                            ?>
                            <tr>
                                <td><?php echo $i; ?></td>
                                <td style="text-transform: capitalize"><?php echo $uliveto->descrizione; ?></td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(array(
                                        "controller" => "admin",
                                        "action" => "modifica-uliveto",
                                        "uliveto" => $uliveto->iduliveto),
                                        "default", true)
                                    ?>">
                                        <button type="button" class="btn btn-warning m-r-xs m-b-xs">Modifica Uliveto
                                        </button>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(array(
                                        "controller" => "admin",
                                        "action" => "elimina-categoria",
                                        "uliveto" => $uliveto->iduliveto),
                                        "default", true)
                                    ?>">
                                        <button type="button" class="btn btn-danger m-r-xs m-b-xs">Elimina Uliveto
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        endforeach;
                        ?>
                        </tbody>
                    </table>
                    <br>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <a href="<?php echo $this->url(array(
                                "controller" => "admin",
                                "action" => "inserisci-categoria"),
                                "default", true)
                            ?>">
                                <button type="button" class="btn btn-success m-r-xs m-b-xs">Inserisci una nuova
                                    Categoria
                                </button>
                            </a>
                        </div>
                    </div>
                </section><!--.proj-page-section-->
            </section><!--.proj-page-->
        </div>

    </div><!--.container-fluid-->
</div><!--.page-content-->

<script>
    $(document).ready(function () {
        $('#datatable').DataTable({
            "language": {
                "url": "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Italian.json"
            },
            "fnInitComplete": function (oSettings, json) {
                $("#datatable_filter").css("float","right").css("width","");
            }
            });
        });

</script>

